on: [push]

jobs:
  build-html:
    runs-on: ubuntu-latest
    name: Build html job
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Sphinx-builder
      uses: JulesFa/sphinx-build@sphinx-builder
      with:
        build-root: "/github/workspace"
